apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: iot-platform
  region: us-east-1
  version: "1.29"
  tags:
    Project: iot-platform
    Environment: dev
    ManagedBy: eksctl

iam:
  withOIDC: true

managedNodeGroups:
  - name: workers
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 50
    volumeType: gp3
    spot: true

    labels:
      role: worker
      environment: dev

    iam:
      withAddonPolicies:
        ebs: true
        albIngress: true
        cloudWatch: true

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

cloudWatch:
  clusterLogging:
    enableTypes: []

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
