apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: iot-platform
  region: us-east-1

managedNodeGroups:
  - name: workers
    instanceType: t3.small
    desiredCapacity: 3 # 改为3个节点
    minSize: 1
    maxSize: 4
    volumeSize: 30
    volumeType: gp3
    spot: false

    labels:
      role: worker
      environment: dev

    iam:
      withAddonPolicies:
        ebs: true
        albIngress: true
        cloudWatch: true
