apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/strimzi/strimzi-kafka-operator
    targetRevision: 0.44.0
    path: examples/kafka/kraft
    directory:
      include: "kafka-ephemeral-single.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
